services:
  redis:
    env_file: .env
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    env_file: .env
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=${USER:-pguser}
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=dbname
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c select"]
      start_period: 30s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ${SUPERCOG_DATA}/postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-init:/docker-entrypoint-initdb.d

  minio:
    env_file: .env
    image: bitnami/minio:latest
    ports:
      - '${MINIO_API_PORT_NUMBER}:${MINIO_API_PORT_NUMBER}'
      - '${MINIO_CONSOLE_PORT_NUMBER}:${MINIO_CONSOLE_PORT_NUMBER}'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${S3_PUBLIC_BUCKET}:public,${S3_FILES_BUCKET_NAME}:public
      - MINIO_API_PORT_NUMBER=${MINIO_API_PORT_NUMBER}
      - MINIO_CONSOLE_PORT_NUMBER=${MINIO_CONSOLE_PORT_NUMBER}
    volumes:
      - minio_data:/bitnami/minio/data

  engine:
    image: supercog.ddns.net/engine:latest
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - SPECIAL_TOOLS=1
      - SUPERCOG_LOCAL_TOOLS=/var/lib/supercog/tools
    volumes:
      - ./local_data/sc_localfiles:/var/lib/supercog
      - ./local_data/tools:/var/lib/supercog/tools

  triggersvc:
    image: supercog.ddns.net/engine:latest
    command: python -m supercog.engine.triggersvc
    depends_on:
      redis:
        condition: service_started
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
      engine:
        condition: service_started
    env_file: .env
    volumes:
      - ./local_data/sc_localfiles:/var/lib/supercog
      - ./local_data/tools:/var/lib/supercog/tools
    ports:
      - "8002:8002"

  dashboard:
    image: supercog.ddns.net/dashboard:latest
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      engine:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - SKIP_EMAIL_VERIFICATION=1

volumes:
  sc_localfiles:
    driver: local
  minio_data:
    driver: local
